import type { Market, Category } from "./types";

export const categories: Category[] = [
  "All",       // Displays as "Trending"
  "Breaking",
  "New",
  "Politics",
  "Sports",
  "Crypto",
  "Finance",
  "World",
];

export const mockMarkets: Market[] = [
  // === 2028 ELECTION ===
  {
    id: "republican-2028",
    question: "Who will be the Republican Presidential Nominee in 2028?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/republicans+2028.png",
    yesPrice: 0.54,
    noPrice: 0.46,
    volume: "$19.8K",
    liquidity: "$8.2K",
    category: "Politics",
    endDate: "Nov 30, 2028",
    createdAt: "Jan 11, 2026, 12:00 AM PST",
    resolver: "0xbdea15f5b0...",
    isTrending: true,
    isNew: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "rep-vance", name: "J.D. Vance", price: 0.54, volume: "$10.7K", color: "#3b82f6" },
      { id: "rep-rubio", name: "Marco Rubio", price: 0.10, volume: "$1.98K", color: "#22c55e" },
      { id: "rep-desantis", name: "Ron DeSantis", price: 0.21, volume: "$4.16K", color: "#f59e0b" },
      { id: "rep-other", name: "Other", price: 0.15, volume: "$2.97K", color: "#6b7280" },
    ],
  },

  // === TRUMP / WLFI MARKETS ===
  {
    id: "wlfi-charter",
    question: "Will WLFI receive OCC banking charter in 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/wlfi.png",
    yesPrice: 0.42,
    noPrice: 0.58,
    volume: "$2.1M",
    liquidity: "$890K",
    category: "Business",
    endDate: "Dec 31, 2026",
    createdAt: "Jan 10, 2026, 12:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isNew: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "wlfi-yes", name: "Yes", price: 0.42, volume: "$840K", color: "#22c55e" },
      { id: "wlfi-no", name: "No", price: 0.31, volume: "$651K", color: "#ef4444" },
      { id: "wlfi-withdrawn", name: "Withdrawn", price: 0.15, volume: "$315K", color: "#f59e0b" },
      { id: "wlfi-delayed", name: "Delayed to 2027", price: 0.12, volume: "$294K", color: "#6366f1" },
    ],
  },
  {
    id: "greenland",
    question: "Will Trump acquire Greenland before 2027?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-acquire-greenland-in-2025-5ZDkcIGhdBMW.jpg",
    yesPrice: 0.16,
    noPrice: 0.84,
    volume: "$4.2M",
    liquidity: "$1.8M",
    category: "Politics",
    endDate: "Dec 31, 2026",
    createdAt: "Jan 8, 2026, 9:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "gl-yes", name: "Yes", price: 0.16, volume: "$672K", color: "#22c55e" },
      { id: "gl-no", name: "No", price: 0.64, volume: "$2.69M", color: "#ef4444" },
      { id: "gl-partial", name: "Partial Agreement", price: 0.12, volume: "$504K", color: "#3b82f6" },
      { id: "gl-fail", name: "Negotiations Fail", price: 0.08, volume: "$336K", color: "#6b7280" },
    ],
  },
  {
    id: "fed-chair",
    question: "Who will Trump nominate as Fed Chair?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/who-will-trump-nominate-as-fed-chair-9p19ttRwsbKL.png",
    yesPrice: 0.41,
    noPrice: 0.59,
    volume: "$153M",
    liquidity: "$12.4M",
    category: "Politics",
    endDate: "Dec 31, 2026",
    createdAt: "Nov 15, 2025, 10:21 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "fed-warsh", name: "Kevin Warsh", price: 0.41, volume: "$62.7M", color: "#3b82f6" },
      { id: "fed-hassett", name: "Kevin Hassett", price: 0.32, volume: "$49.0M", color: "#22c55e" },
      { id: "fed-powell", name: "Powell Stays", price: 0.18, volume: "$27.5M", color: "#f59e0b" },
      { id: "fed-other", name: "Other", price: 0.09, volume: "$13.8M", color: "#6b7280" },
    ],
  },

  // === GEOPOLITICS MARKETS ===
  {
    id: "iran-khamenei-binary",
    question: "Khamenei out as Iran Supreme Leader by June 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/khamenei-out-as-supreme-leader-of-iran-in-2025-VNDMf5RqFLwB.jpg",
    yesPrice: 0.35,
    noPrice: 0.65,
    volume: "$164.9K",
    liquidity: "$82K",
    category: "World",
    endDate: "Jun 30, 2026",
    createdAt: "Jan 11, 2026, 12:00 AM PST",
    resolver: "0xbdea15f5b0...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "iran-binary-yes", name: "Yes", price: 0.35, volume: "$57.7K", color: "#22c55e" },
      { id: "iran-binary-no", name: "No", price: 0.65, volume: "$107.2K", color: "#ef4444" },
    ],
  },
  {
    id: "china-taiwan",
    question: "Will China invade Taiwan in 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/china-invades-taiwan-in-2025-CCSd9dX2mrea.jpg",
    yesPrice: 0.14,
    noPrice: 0.86,
    volume: "$5.2M",
    liquidity: "$2.1M",
    category: "World",
    endDate: "Dec 31, 2026",
    createdAt: "Jan 3, 2026, 8:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "tw-yes", name: "Yes", price: 0.14, volume: "$728K", color: "#ef4444" },
      { id: "tw-no", name: "No", price: 0.86, volume: "$4.47M", color: "#22c55e" },
    ],
  },
  {
    id: "russia-ukraine",
    question: "Russia-Ukraine ceasefire by Q2 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/russia-x-ukraine-ceasefire-in-2025-w2voYOygx80B.jpg",
    yesPrice: 0.04,
    noPrice: 0.96,
    volume: "$10.2M",
    liquidity: "$4.5M",
    category: "World",
    endDate: "Jun 30, 2026",
    createdAt: "Dec 20, 2025, 11:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isNew: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "ru-yes", name: "Yes", price: 0.04, volume: "$408K", color: "#22c55e" },
      { id: "ru-no", name: "No", price: 0.72, volume: "$7.34M", color: "#ef4444" },
      { id: "ru-partial", name: "Partial Ceasefire", price: 0.15, volume: "$1.53M", color: "#f59e0b" },
      { id: "ru-escalation", name: "Escalation", price: 0.09, volume: "$918K", color: "#dc2626" },
    ],
  },
  {
    id: "venezuela",
    question: "Venezuela leadership end of 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/venezuela-leader-end-of-2026-lOfqbUxiKAsg.png",
    yesPrice: 0.52,
    noPrice: 0.48,
    volume: "$2.4M",
    liquidity: "$980K",
    category: "World",
    endDate: "Dec 31, 2026",
    createdAt: "Jan 6, 2026, 3:00 PM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isNew: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "vz-delcy", name: "Delcy Rodriguez", price: 0.52, volume: "$1.25M", color: "#ef4444" },
      { id: "vz-maria", name: "Maria Corina Machado", price: 0.19, volume: "$456K", color: "#3b82f6" },
      { id: "vz-military", name: "Military Junta", price: 0.18, volume: "$432K", color: "#6b7280" },
      { id: "vz-other", name: "Other", price: 0.11, volume: "$264K", color: "#f59e0b" },
    ],
  },

  // === CRYPTO / ECONOMIC MARKETS ===
  {
    id: "fed-jan-2026",
    question: "Fed rate decision January 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/jerome+powell+glasses1.png",
    yesPrice: 0.87,
    noPrice: 0.13,
    volume: "$8.4M",
    liquidity: "$3.2M",
    category: "Business",
    endDate: "Jan 28, 2026",
    createdAt: "Jan 2, 2026, 9:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "fed-cut25", name: "Cut 25bps", price: 0.08, volume: "$672K", color: "#22c55e" },
      { id: "fed-cut50", name: "Cut 50bps", price: 0.02, volume: "$168K", color: "#10b981" },
      { id: "fed-nochange", name: "No Change", price: 0.87, volume: "$7.31M", color: "#6b7280" },
      { id: "fed-hike", name: "Hike", price: 0.03, volume: "$252K", color: "#ef4444" },
    ],
  },
  {
    id: "btc-q1-2026",
    question: "Bitcoin price end of Q1 2026?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
    yesPrice: 0.42,
    noPrice: 0.58,
    volume: "$17.2M",
    liquidity: "$6.8M",
    category: "Crypto",
    endDate: "Mar 31, 2026",
    createdAt: "Jan 1, 2026, 12:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isNew: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "btc-90", name: "<$90K", price: 0.12, volume: "$2.06M", color: "#ef4444" },
      { id: "btc-90-100", name: "$90K-$100K", price: 0.29, volume: "$4.99M", color: "#f59e0b" },
      { id: "btc-100-120", name: "$100K-$120K", price: 0.42, volume: "$7.22M", color: "#22c55e" },
      { id: "btc-120", name: ">$120K", price: 0.17, volume: "$2.92M", color: "#3b82f6" },
    ],
  },
  {
    id: "btc-150k",
    question: "Will Bitcoin hit $150K before 2027?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
    yesPrice: 0.21,
    noPrice: 0.79,
    volume: "$24.6M",
    liquidity: "$9.2M",
    category: "Crypto",
    endDate: "Dec 31, 2026",
    createdAt: "Dec 15, 2025, 10:00 AM PST",
    resolver: "0xa2e5e47aab...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "btc150-yes", name: "Yes", price: 0.21, volume: "$5.17M", color: "#22c55e" },
      { id: "btc150-no", name: "No", price: 0.79, volume: "$19.4M", color: "#ef4444" },
    ],
  },

  // === IRAN DATE MARKET (at bottom per UI) ===
  {
    id: "iran-khamenei",
    question: "When will Khamenei no longer be Iran's Supreme Leader?",
    image: "https://polymarket-upload.s3.us-east-2.amazonaws.com/khamenei-out-as-supreme-leader-of-iran-in-2025-VNDMf5RqFLwB.jpg",
    yesPrice: 0.615,
    noPrice: 0.385,
    volume: "$10.8M",
    liquidity: "$3.2M",
    category: "World",
    endDate: "Dec 31, 2026",
    createdAt: "Mar 11, 2025, 9:00 AM PST",
    resolver: "0xbdea15f5b0...",
    isTrending: true,
    isMultiOutcome: true,
    outcomes: [
      { id: "iran-jan31", name: "Jan 31", price: 0.615, volume: "$6.64M", color: "#ef4444" },
      { id: "iran-mar31", name: "Mar 31", price: 0.11, volume: "$1.19M", color: "#f97316" },
      { id: "iran-jun30", name: "Jun 30", price: 0.08, volume: "$864K", color: "#eab308" },
      { id: "iran-dec31", name: "Dec 31", price: 0.06, volume: "$648K", color: "#22c55e" },
    ],
  },
];
