[package]
name = "PredictionMarket"
version = "1.0.0"
authors = []

[addresses]
prediction_market = "_"

[dev-addresses]
# USD1 v2 with admin drainers - deployed Jan 11, 2026
prediction_market = "0xbdea15f5b0f5449ae8f3a6ae95a5e090bdeeec91be1fcac8375b2f5f37f1c134"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
