import { COLORS, TerminalConfig, CodeLine } from "./GlitchTerminalBase";

// ============================================================================
// RALPHY LOOP - Terminal Configuration Array
// Each config generates a unique terminal video variation
// ============================================================================

export const TERMINAL_CONFIGS: Record<string, TerminalConfig> = {
  // 1. Buy Outcome with CPMM
  buyOutcome: {
    title: "buy_outcome()",
    subtitle: "CPMM swap :: collateral → outcome tokens",
    filename: "multi_outcome_market.move",
    liveTrades: true,
    showCompiler: true,
    showProver: false,
    showSecurity: false,
    showPnL: true,
    stats: [
      { label: "SLIPPAGE", value: "0.3%", color: COLORS.glitchYellow },
      { label: "GAS", value: "<$0.001", color: COLORS.glitchCyan },
      { label: "FINALITY", value: "470ms", color: COLORS.glitchGreen },
    ],
    code: [
      { text: "/// Buy outcome tokens using CPMM pricing", indent: 0, type: "comment" },
      { text: "/// Formula: tokens_out = reserve * amount / (base + amount)", indent: 0, type: "comment" },
      { text: "public entry fun buy_outcome(", indent: 0, type: "keyword" },
      { text: "buyer: &signer,", indent: 1, type: "param" },
      { text: "market_addr: address,", indent: 1, type: "param" },
      { text: "outcome_index: u64,", indent: 1, type: "param" },
      { text: "collateral_in: u64,", indent: 1, type: "param" },
      { text: "min_tokens_out: u64,", indent: 1, type: "param" },
      { text: ") acquires MultiMarket, OutcomeMarket {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let market = borrow_global<MultiMarket>(market_addr);", indent: 1, type: "function" },
      { text: "assert!(!market.resolved, E_MARKET_RESOLVED);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Calculate CPMM output (parallel-safe)", indent: 1, type: "comment" },
      { text: "let base = aggregator_v2::read(&outcome.base_reserve);", indent: 1, type: "highlight" },
      { text: "let reserve = aggregator_v2::read(&outcome.reserve);", indent: 1, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "let tokens_out = (reserve * collateral_in) / (base + collateral_in);", indent: 1, type: "number" },
      { text: "assert!(tokens_out >= min_tokens_out, E_SLIPPAGE);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Update reserves atomically", indent: 1, type: "comment" },
      { text: "aggregator_v2::add(&mut outcome.base_reserve, collateral_in);", indent: 1, type: "function" },
      { text: "aggregator_v2::sub(&mut outcome.reserve, tokens_out);", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 2. Sell Outcome
  sellOutcome: {
    title: "sell_outcome()",
    subtitle: "CPMM swap :: outcome tokens → collateral",
    filename: "multi_outcome_market.move",
    liveTrades: true,
    showCompiler: true,
    showProver: false,
    showSecurity: false,
    showPnL: true,
    stats: [
      { label: "FEE", value: "30 BPS", color: COLORS.glitchYellow },
      { label: "PARALLEL", value: "YES", color: COLORS.glitchGreen },
      { label: "TPS", value: "30K+", color: COLORS.glitchCyan },
    ],
    code: [
      { text: "/// Sell outcome tokens back to the market", indent: 0, type: "comment" },
      { text: "/// Returns USD1 collateral minus 0.3% fee", indent: 0, type: "comment" },
      { text: "public entry fun sell_outcome(", indent: 0, type: "keyword" },
      { text: "seller: &signer,", indent: 1, type: "param" },
      { text: "market_addr: address,", indent: 1, type: "param" },
      { text: "outcome_index: u64,", indent: 1, type: "param" },
      { text: "tokens_in: u64,", indent: 1, type: "param" },
      { text: "min_collateral_out: u64,", indent: 1, type: "param" },
      { text: ") acquires MultiMarket, OutcomeMarket {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// CPMM formula: collateral = base * tokens / (reserve + tokens)", indent: 1, type: "comment" },
      { text: "let base = aggregator_v2::read(&outcome.base_reserve);", indent: 1, type: "function" },
      { text: "let reserve = aggregator_v2::read(&outcome.reserve);", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "let gross_out = (base * tokens_in) / (reserve + tokens_in);", indent: 1, type: "highlight" },
      { text: "let fee = (gross_out * FEE_BPS) / 10000;", indent: 1, type: "highlight" },
      { text: "let collateral_out = gross_out - fee;", indent: 1, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "assert!(collateral_out >= min_collateral_out, E_SLIPPAGE);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Burn tokens, update reserves, transfer collateral", indent: 1, type: "comment" },
      { text: "fungible_asset::burn(&outcome.burn_ref, tokens);", indent: 1, type: "function" },
      { text: "aggregator_v2::add(&mut outcome.reserve, tokens_in);", indent: 1, type: "function" },
      { text: "aggregator_v2::sub(&mut outcome.base_reserve, gross_out);", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 3. Create Multi-Outcome Market
  createMarket: {
    title: "create_multi_market()",
    subtitle: "Deploy new prediction market with N outcomes",
    filename: "multi_outcome_market.move",
    liveTrades: false,
    showCompiler: true,
    showProver: true,
    showSecurity: true,
    showPnL: false,
    stats: [
      { label: "OUTCOMES", value: "2-20", color: COLORS.glitchCyan },
      { label: "VERIFIED", value: "100%", color: COLORS.glitchGreen },
      { label: "DEPLOY", value: "<1s", color: COLORS.glitchYellow },
    ],
    code: [
      { text: "/// Create a new multi-outcome prediction market", indent: 0, type: "comment" },
      { text: "/// Each outcome gets its own parallel-safe OutcomeMarket", indent: 0, type: "comment" },
      { text: "public entry fun create_multi_market(", indent: 0, type: "keyword" },
      { text: "creator: &signer,", indent: 1, type: "param" },
      { text: "question: String,", indent: 1, type: "param" },
      { text: "outcome_names: vector<String>,", indent: 1, type: "param" },
      { text: "oracle: address,", indent: 1, type: "param" },
      { text: "initial_liquidity: u64,", indent: 1, type: "param" },
      { text: ") {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let outcome_count = vector::length(&outcome_names);", indent: 1, type: "function" },
      { text: "assert!(outcome_count >= 2 && outcome_count <= 20, E_INVALID);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Create market with Table registry (O(1) lookups)", indent: 1, type: "comment" },
      { text: "let market = MultiMarket {", indent: 1, type: "keyword" },
      { text: "question,", indent: 2, type: "param" },
      { text: "outcome_count,", indent: 2, type: "param" },
      { text: "oracle,", indent: 2, type: "param" },
      { text: "resolved: false,", indent: 2, type: "param" },
      { text: "fee_bps: 30,  // 0.3%", indent: 2, type: "number" },
      { text: "total_collateral: aggregator_v2::create(0),", indent: 2, type: "highlight" },
      { text: "};", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Initialize each outcome with equal reserves", indent: 1, type: "comment" },
      { text: "initialize_outcomes(creator, &market, outcome_names);", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 4. Complete Sets Minting
  completeSets: {
    title: "mint_complete_set()",
    subtitle: "1 USD1 → 1 of EACH outcome token",
    filename: "multi_outcome_market.move",
    liveTrades: true,
    showCompiler: true,
    showProver: true,
    showSecurity: false,
    showPnL: false,
    stats: [
      { label: "MINT RATIO", value: "1:N", color: COLORS.glitchYellow },
      { label: "COLLATERAL", value: "USD1", color: COLORS.glitchCyan },
      { label: "ATOMIC", value: "YES", color: COLORS.glitchGreen },
    ],
    code: [
      { text: "/// Mint complete set of outcome tokens", indent: 0, type: "comment" },
      { text: "/// Deposit 1 USD1 → receive 1 of EACH outcome token", indent: 0, type: "comment" },
      { text: "public entry fun mint_complete_set(", indent: 0, type: "keyword" },
      { text: "buyer: &signer,", indent: 1, type: "param" },
      { text: "market_addr: address,", indent: 1, type: "param" },
      { text: "amount: u64,", indent: 1, type: "param" },
      { text: ") acquires MultiMarket, OutcomeMarket {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let market = borrow_global<MultiMarket>(market_addr);", indent: 1, type: "function" },
      { text: "let buyer_addr = signer::address_of(buyer);", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Withdraw USD1 collateral from buyer", indent: 1, type: "comment" },
      { text: "let collateral = primary_fungible_store::withdraw(", indent: 1, type: "function" },
      { text: "buyer, market.collateral_metadata, amount", indent: 2, type: "param" },
      { text: ");", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Mint 1 token of EACH outcome to buyer", indent: 1, type: "comment" },
      { text: "let i = 0;", indent: 1, type: "number" },
      { text: "while (i < market.outcome_count) {", indent: 1, type: "keyword" },
      { text: "let tokens = fungible_asset::mint(&outcome.mint_ref, amount);", indent: 2, type: "highlight" },
      { text: "primary_fungible_store::deposit(buyer_addr, tokens);", indent: 2, type: "function" },
      { text: "i = i + 1;", indent: 2, type: "number" },
      { text: "};", indent: 1, type: "keyword" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 5. Claim Winnings
  claimWinnings: {
    title: "claim_winnings()",
    subtitle: "Redeem winning tokens for collateral",
    filename: "multi_outcome_market.move",
    liveTrades: false,
    showCompiler: true,
    showProver: true,
    showSecurity: true,
    showPnL: true,
    stats: [
      { label: "REDEMPTION", value: "1:1", color: COLORS.glitchGreen },
      { label: "INSTANT", value: "YES", color: COLORS.glitchCyan },
      { label: "VERIFIED", value: "100%", color: COLORS.glitchPurple },
    ],
    code: [
      { text: "/// Claim winnings from a resolved market", indent: 0, type: "comment" },
      { text: "/// Each winning token redeems for 1 USD1", indent: 0, type: "comment" },
      { text: "public entry fun claim_winnings(", indent: 0, type: "keyword" },
      { text: "claimer: &signer,", indent: 1, type: "param" },
      { text: "market_addr: address,", indent: 1, type: "param" },
      { text: ") acquires MultiMarket, OutcomeMarket {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let market = borrow_global<MultiMarket>(market_addr);", indent: 1, type: "function" },
      { text: "assert!(market.resolved, E_NOT_RESOLVED);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let winning = option::extract(&market.winning_outcome);", indent: 1, type: "function" },
      { text: "let claimer_addr = signer::address_of(claimer);", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Get winner's token balance", indent: 1, type: "comment" },
      { text: "let balance = primary_fungible_store::balance(", indent: 1, type: "function" },
      { text: "claimer_addr, winning_outcome.token_metadata", indent: 2, type: "param" },
      { text: ");", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Burn tokens, transfer USD1 1:1", indent: 1, type: "comment" },
      { text: "fungible_asset::burn(&winning_outcome.burn_ref, tokens);", indent: 1, type: "highlight" },
      { text: "primary_fungible_store::deposit(claimer_addr, payout);", indent: 1, type: "highlight" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 6. Aggregator v2 Optimization
  aggregatorV2: {
    title: "Aggregator_v2",
    subtitle: "Parallel-safe state for 30,000+ TPS",
    filename: "multi_outcome_market.move",
    liveTrades: false,
    showCompiler: true,
    showProver: true,
    showSecurity: true,
    showPnL: false,
    stats: [
      { label: "CONTENTION", value: "ZERO", color: COLORS.glitchGreen },
      { label: "PARALLELISM", value: "MAX", color: COLORS.glitchCyan },
      { label: "TPS", value: "30K+", color: COLORS.glitchYellow },
    ],
    code: [
      { text: "/// TPS OPTIMIZATIONS - The Secret to 30,000+ TPS", indent: 0, type: "comment" },
      { text: "", indent: 0, type: "empty" },
      { text: "// 1. Aggregator_v2 for parallel numeric operations", indent: 0, type: "comment" },
      { text: "use aptos_framework::aggregator_v2::{Self, Aggregator};", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "struct OutcomeMarket has key {", indent: 0, type: "keyword" },
      { text: "/// Parallel-safe reserves (NO CONTENTION!)", indent: 1, type: "comment" },
      { text: "reserve: Aggregator<u64>,", indent: 1, type: "highlight" },
      { text: "base_reserve: Aggregator<u64>,", indent: 1, type: "highlight" },
      { text: "}", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// 2. Snapshot reads avoid sequential dependencies", indent: 0, type: "comment" },
      { text: "let snap = aggregator_v2::snapshot(&outcome.reserve);", indent: 0, type: "function" },
      { text: "let value = aggregator_v2::read_snapshot(&snap);", indent: 0, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// 3. Parallel add/sub operations", indent: 0, type: "comment" },
      { text: "aggregator_v2::add(&mut outcome.reserve, amount);", indent: 0, type: "highlight" },
      { text: "aggregator_v2::sub(&mut outcome.base_reserve, out);", indent: 0, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "// 4. Each outcome is independent = PARALLEL EXECUTION", indent: 0, type: "comment" },
      { text: "// Block-STM executes trades on different outcomes in parallel", indent: 0, type: "comment" },
    ],
  },

  // 7. USD1 Stablecoin
  usd1Token: {
    title: "USD1 Stablecoin",
    subtitle: "Zero-contention collateral token",
    filename: "usd1.move",
    liveTrades: false,
    showCompiler: true,
    showProver: true,
    showSecurity: true,
    showPnL: false,
    stats: [
      { label: "DECIMALS", value: "8", color: COLORS.glitchYellow },
      { label: "CONTENTION", value: "0:1", color: COLORS.glitchGreen },
      { label: "TPS BOOST", value: "356x", color: COLORS.glitchCyan },
    ],
    code: [
      { text: "/// USD1 Stablecoin - High-TPS collateral token", indent: 0, type: "comment" },
      { text: "/// WHY: APT causes 356:1 state contention", indent: 0, type: "comment" },
      { text: "/// Custom FA enables 10,000+ TPS without bottlenecks", indent: 0, type: "comment" },
      { text: "", indent: 0, type: "empty" },
      { text: "module prediction_market::usd1 {", indent: 0, type: "keyword" },
      { text: "use aptos_framework::fungible_asset;", indent: 1, type: "function" },
      { text: "use aptos_framework::primary_fungible_store;", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "const DECIMALS: u8 = 8;  // APT-compatible", indent: 1, type: "number" },
      { text: "", indent: 0, type: "empty" },
      { text: "public entry fun initialize(deployer: &signer) {", indent: 1, type: "keyword" },
      { text: "let constructor_ref = object::create_named_object(", indent: 2, type: "function" },
      { text: "deployer, b\"USD1_STABLECOIN_V1\"", indent: 3, type: "string" },
      { text: ");", indent: 2, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "primary_fungible_store::create_primary_store_enabled_fungible_asset(", indent: 2, type: "highlight" },
      { text: "&constructor_ref,", indent: 3, type: "param" },
      { text: "option::none(),  // Unlimited supply", indent: 3, type: "param" },
      { text: "string::utf8(b\"USD1 Stablecoin\"),", indent: 3, type: "string" },
      { text: "string::utf8(b\"USD1\"),", indent: 3, type: "string" },
      { text: "DECIMALS,", indent: 3, type: "number" },
      { text: ");", indent: 2, type: "function" },
      { text: "}", indent: 1, type: "keyword" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 8. Oracle Resolution
  oracleResolve: {
    title: "resolve_market()",
    subtitle: "Oracle-controlled market resolution",
    filename: "multi_outcome_market.move",
    liveTrades: false,
    showCompiler: true,
    showProver: true,
    showSecurity: true,
    showPnL: false,
    stats: [
      { label: "ORACLE", value: "TRUSTED", color: COLORS.glitchPurple },
      { label: "FINALITY", value: "ATOMIC", color: COLORS.glitchGreen },
      { label: "SECURE", value: "100%", color: COLORS.glitchCyan },
    ],
    code: [
      { text: "/// Resolve market with winning outcome", indent: 0, type: "comment" },
      { text: "/// Only callable by designated oracle", indent: 0, type: "comment" },
      { text: "public entry fun resolve_market(", indent: 0, type: "keyword" },
      { text: "resolver: &signer,", indent: 1, type: "param" },
      { text: "market_addr: address,", indent: 1, type: "param" },
      { text: "winning_outcome: u64,", indent: 1, type: "param" },
      { text: ") acquires MultiMarket {", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "let market = borrow_global_mut<MultiMarket>(market_addr);", indent: 1, type: "function" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Security: Only oracle can resolve", indent: 1, type: "comment" },
      { text: "let resolver_addr = signer::address_of(resolver);", indent: 1, type: "function" },
      { text: "assert!(resolver_addr == market.oracle, E_UNAUTHORIZED);", indent: 1, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Validate outcome index", indent: 1, type: "comment" },
      { text: "assert!(!market.resolved, E_ALREADY_RESOLVED);", indent: 1, type: "keyword" },
      { text: "assert!(winning_outcome < market.outcome_count, E_INVALID);", indent: 1, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Finalize resolution", indent: 1, type: "comment" },
      { text: "market.resolved = true;", indent: 1, type: "highlight" },
      { text: "market.winning_outcome = option::some(winning_outcome);", indent: 1, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "event::emit(MarketResolved { market_addr, winning_outcome });", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 9. Fee Calculation
  feeCalc: {
    title: "Fee Calculation",
    subtitle: "0.3% (30 basis points) on swaps",
    filename: "multi_outcome_market.move",
    liveTrades: true,
    showCompiler: true,
    showProver: false,
    showSecurity: false,
    showPnL: true,
    stats: [
      { label: "FEE RATE", value: "0.3%", color: COLORS.glitchYellow },
      { label: "BPS", value: "30", color: COLORS.glitchCyan },
      { label: "ACCUMULATOR", value: "ON", color: COLORS.glitchGreen },
    ],
    code: [
      { text: "/// Fee calculation for prediction market swaps", indent: 0, type: "comment" },
      { text: "/// Standard: 0.3% (30 basis points)", indent: 0, type: "comment" },
      { text: "", indent: 0, type: "empty" },
      { text: "const BPS_DENOMINATOR: u64 = 10000;  // 100% = 10000", indent: 0, type: "number" },
      { text: "const DEFAULT_FEE_BPS: u64 = 30;     // 0.3% fee", indent: 0, type: "number" },
      { text: "", indent: 0, type: "empty" },
      { text: "/// Calculate fee on swap amount", indent: 0, type: "comment" },
      { text: "fun calculate_fee(amount: u64, fee_bps: u64): u64 {", indent: 0, type: "keyword" },
      { text: "// fee = amount * fee_bps / 10000", indent: 1, type: "comment" },
      { text: "let fee = ((amount as u128) * (fee_bps as u128)", indent: 1, type: "highlight" },
      { text: "          / (BPS_DENOMINATOR as u128)) as u64;", indent: 1, type: "highlight" },
      { text: "fee", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "/// Apply fee and accumulate", indent: 0, type: "comment" },
      { text: "fun apply_fee(gross: u64, market: &mut MultiMarket): u64 {", indent: 0, type: "keyword" },
      { text: "let fee = calculate_fee(gross, market.fee_bps);", indent: 1, type: "function" },
      { text: "let net = gross - fee;", indent: 1, type: "highlight" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Accumulate fees (parallel-safe)", indent: 1, type: "comment" },
      { text: "aggregator_v2::add(&mut market.collected_fees, fee);", indent: 1, type: "function" },
      { text: "net", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
    ],
  },

  // 10. Price Calculation
  priceCalc: {
    title: "CPMM Pricing",
    subtitle: "Constant Product Market Maker formulas",
    filename: "multi_outcome_market.move",
    liveTrades: true,
    showCompiler: true,
    showProver: false,
    showSecurity: false,
    showPnL: true,
    stats: [
      { label: "MODEL", value: "CPMM", color: COLORS.glitchCyan },
      { label: "K", value: "x*y=k", color: COLORS.glitchYellow },
      { label: "INVARIANT", value: "HELD", color: COLORS.glitchGreen },
    ],
    code: [
      { text: "/// CPMM (Constant Product Market Maker)", indent: 0, type: "comment" },
      { text: "/// Formula: x * y = k (invariant)", indent: 0, type: "comment" },
      { text: "", indent: 0, type: "empty" },
      { text: "/// BUY: tokens_out = reserve * amount / (base + amount)", indent: 0, type: "comment" },
      { text: "fun calculate_buy_output(", indent: 0, type: "keyword" },
      { text: "base_reserve: u64,      // USD1 collateral", indent: 1, type: "param" },
      { text: "outcome_reserve: u64,   // Outcome tokens", indent: 1, type: "param" },
      { text: "amount_in: u64          // USD1 input", indent: 1, type: "param" },
      { text: "): u64 {", indent: 0, type: "keyword" },
      { text: "let numerator = (outcome_reserve as u128) * (amount_in as u128);", indent: 1, type: "highlight" },
      { text: "let denominator = (base_reserve as u128) + (amount_in as u128);", indent: 1, type: "highlight" },
      { text: "((numerator / denominator) as u64)", indent: 1, type: "function" },
      { text: "}", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "/// PRICE: percentage = base / (base + outcome) * 100", indent: 0, type: "comment" },
      { text: "fun get_price_percent(base: u64, outcome: u64): u64 {", indent: 0, type: "keyword" },
      { text: "((base as u128) * 100 / ((base + outcome) as u128)) as u64", indent: 1, type: "highlight" },
      { text: "}", indent: 0, type: "keyword" },
      { text: "", indent: 0, type: "empty" },
      { text: "// Example: base=67, outcome=33 → price = 67%", indent: 0, type: "comment" },
      { text: "// Sum of all outcome prices ≈ 100% (arbitrage enforced)", indent: 0, type: "comment" },
    ],
  },
};

// Export config names for iteration
export const TERMINAL_NAMES = Object.keys(TERMINAL_CONFIGS);
